; generated by PrusaSlicer 2.9.4 on 2026-01-10 at 20:34:02 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.70mm

M104 S200 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
G1 E-2 F2400
G92 E0
G1 Z.35 F7800
G1 X92.497 Y95.956
G1 E2 F2400
;TYPE:Skirt/Brim
;WIDTH:0.7
G1 F734
G1 X94.196 Y94.499 E2.20352
G1 X95.584 Y93.895 E2.34116
G1 X97.393 Y93.565 E2.50837
G1 X98.793 Y93.534 E2.6357
G1 X100.955 Y94.112 E2.83919
G1 X102.779 Y95.409 E3.0427
G1 X103.806 Y96.796 E3.19963
G1 X104.6 Y98.248 E3.35011
G1 X105.344 Y100.667 E3.58024
G1 X105.174 Y102.898 E3.78369
G1 X104.236 Y104.931 E3.98728
G1 X102.648 Y106.508 E4.19078
G1 X100.051 Y107.546 E4.44509
G1 X98.035 Y107.56 E4.62841
G1 X97.567 Y107.472 E4.67171
G1 X96.443 Y107.12 E4.77881
G1 X95.222 Y106.625 E4.89861
G1 X94.247 Y106.128 E4.99812
G1 X92.351 Y104.327 E5.2359
G1 X91.362 Y102.075 E5.45955
G1 X91.185 Y101.271 E5.53441
G1 X91.392 Y97.974 E5.8348
G1 X92.468 Y96.008 E6.03859
G1 E4.03859 F2400
G92 E0
G92 E0
G1 X97.749 Y100.537 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:0.448061
G1 F734
G1 X98.131 Y100.667 E2.0219
;WIDTH:0.415111
G1 X98.692 Y101.079 E2.05634
G1 X98.37 Y100.843 F7800
;LAYER_CHANGE
;Z:0.65
;HEIGHT:0.3
G1 Z.65 F7800
G1 X97.822 Y100.56
;WIDTH:0.404381
G1 F600
G1 X97.98 Y100.691 E2.06504
G1 X98.127 Y100.746 E2.0717
;WIDTH:0.451469
G1 X98.342 Y100.88 E2.08393
;WIDTH:0.498557
G1 X98.557 Y101.013 E2.09762
;WIDTH:0.545645
G1 X98.772 Y101.147 E2.11283
;WIDTH:0.592733
G1 X98.987 Y101.281 E2.12952
G1 X99.196 Y101.468 E2.148
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X99.275 Y101.575 E2.15495
G1 X98.951 Y101.34 F7800
G1 E.15495 F2400
G92 E0
G1 X100.172 Y98.35 F7800
G1 E2 F2400
G1 F900
G1 X100.109 Y98.387 E2.00382
G1 X100.172 Y98.424 E2.00764
G1 X100.194 Y98.387 E2.00989
;LAYER_CHANGE
;Z:0.95
;HEIGHT:0.3
G1 Z.95 F7800
G1 X100.619 Y98.721
;TYPE:External perimeter
;WIDTH:0.729751
G1 F600
G1 X100.59 Y98.814 E2.01797
;WIDTH:0.763377
G1 X100.56 Y98.907 E2.02649
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X100.54 Y98.97 E2.02994
G1 X100.532 Y99.379 E2.05131
;TYPE:External perimeter
;WIDTH:0.539056
;HEIGHT:0.3
G1 F600
G1 X100.532 Y99.381 E2.05143
;WIDTH:0.497647
G1 X100.532 Y99.383 E2.05154
;WIDTH:0.456239
G1 X100.532 Y99.385 E2.05164
;WIDTH:0.414765
G1 X100.358 Y99.813 E2.07183
;WIDTH:0.456109
G1 X100.184 Y100.239 E2.09431
;WIDTH:0.476125
G1 X100.218 Y100.284 E2.09721
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X100.274 Y100.358 E2.10206
G1 X100.73 Y100.644 E2.13018
G1 X101.154 Y100.959 E2.15778
G1 X101.304 Y101.176 E2.17156
G1 X101.042 Y101.155 E2.18529
G1 X100.539 Y100.957 E2.21353
G1 X100.076 Y100.682 E2.24166
G1 X99.867 Y100.495 E2.25631
;TYPE:External perimeter
;WIDTH:0.456109
;HEIGHT:0.3
G1 F600
G1 X99.795 Y100.276 E2.26757
G1 X99.903 Y99.956 E2.28407
;WIDTH:0.418563
G1 X100.249 Y99.266 E2.31817
;WIDTH:0.417436
G1 X100.268 Y99.247 E2.31935
;WIDTH:0.461451
G1 X100.287 Y99.227 E2.32072
;WIDTH:0.505465
G1 X100.306 Y99.208 E2.3222
;WIDTH:0.54948
G1 X100.325 Y99.189 E2.32383
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X100.498 Y99.013 E2.33672
G1 X100.536 Y99.411 F7800
G1 E.33672 F2400
G92 E0
G1 X97.89 Y100.584 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:0.404381
;HEIGHT:0.3
G1 F600
G1 X97.869 Y100.621 E2.0018
G1 X97.805 Y100.584 E2.00493
G1 X97.869 Y100.548 E2.00804
G1 E.00804 F2400
G92 E0
G1 X99.426 Y101.853 F7800
G1 E2 F2400
;WIDTH:0.37664
G1 F600
G1 X99.639 Y102.125 E2.01346
;WIDTH:0.37733
G1 X99.742 Y102.452 E2.02684
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X99.759 Y102.506 E2.0298
G1 X99.688 Y102.55 E2.03416
G1 X99.6 Y102.536 E2.03882
;TYPE:External perimeter
;WIDTH:0.380141
;HEIGHT:0.3
G1 F600
G1 X99.481 Y102.516 E2.04357
G1 X99.379 Y102.289 E2.05337
;WIDTH:0.37664
G1 X99.341 Y101.995 E2.06492
G1 X99.395 Y101.905 E2.06901
G1 X99.672 Y102.194 F7800
M106 S255
;LAYER_CHANGE
;Z:1.25
;HEIGHT:0.3
G1 E.06901 F2400
G92 E0
G1 Z1.25 F7800
G1 X100.77 Y98.609
G1 E2 F2400
;WIDTH:0.404381
G1 F600
G1 X100.675 Y98.816 E2.00966
G1 X100.85 Y100.694 F7800
;WIDTH:0.57018
G1 F600
G1 X101.202 Y100.85 E2.03395
G1 X101.508 Y101.048 E2.05694
G1 X101.564 Y101.197 E2.06698
G1 X101.557 Y101.374 E2.07815
G1 X101.402 Y101.604 E2.09565
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X101.323 Y101.722 E2.10307
G1 X101.368 Y101.758 E2.10608
G1 X101.362 Y101.904 E2.11371
G1 X100.961 Y102.191 E2.13947
G1 X100.514 Y102.416 E2.16562
G1 X100.166 Y102.546 E2.18503
;TYPE:External perimeter
;WIDTH:0.507277
;HEIGHT:0.3
G1 F600
G1 X100.018 Y102.601 E2.19375
G1 X99.783 Y102.639 E2.2069
G1 X99.529 Y102.602 E2.22108
G1 X99.425 Y102.541 E2.22774
G1 X99.435 Y102.392 E2.23599
G1 X99.584 Y102.278 E2.24635
G1 X100.059 Y102.12 E2.274
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X100.623 Y101.963 E2.30459
G1 X101.02 Y101.659 E2.33071
G1 X101.108 Y101.631 E2.33553
G1 X101.111 Y101.597 E2.33731
;TYPE:External perimeter
;WIDTH:0.57018
;HEIGHT:0.3
G1 F600
G1 X101.122 Y101.425 E2.34818
G1 X100.871 Y100.751 E2.39355
G1 X101.252 Y100.87 F7800
G1 E.39355 F2400
G92 E0
G1 X97.544 Y98.35 F7800
G1 E2 F2400
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X97.444 Y98.116 E2.01329
G1 E.01329 F2400
G92 E0
G1 X98.689 Y103.264 F7800
G1 E2 F2400
G1 F900
G1 X98.723 Y103.109 E2.00829
;LAYER_CHANGE
;Z:1.55
;HEIGHT:0.3
G1 E.00829 F2400
G92 E0
G1 Z1.55 F7800
G1 X100.545 Y98.078
G1 E2 F2400
;HEIGHT:0.4
G1 F900
G1 X100.611 Y98.224 E2.00837
;TYPE:External perimeter
;WIDTH:0.404381
;HEIGHT:0.3
G1 F600
G1 X100.825 Y98.697 E2.03039
G1 X101.011 Y98.953 E2.04381
;WIDTH:0.365915
G1 X101.011 Y98.954 E2.04385
;WIDTH:0.327449
G1 X101.012 Y98.954 E2.04388
;WIDTH:0.288983
G1 X101.013 Y98.955 E2.04392
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X101.205 Y99.086 E2.05606
G1 X101.411 Y98.923 E2.06978
G1 X101.373 Y98.721 E2.08052
G1 X101.178 Y98.222 E2.10851
G1 X101.154 Y97.757 E2.13284
G1 X101.248 Y97.36 E2.15415
G1 X101.544 Y96.917 E2.18199
G1 X101.909 Y96.636 E2.20606
G1 X102.233 Y96.495 E2.22452
G1 X102.666 Y96.424 E2.24744
G1 X102.967 Y96.462 E2.26329
G1 X103.444 Y96.658 E2.29023
G1 X103.795 Y96.959 E2.31439
G1 X104.046 Y97.397 E2.34076
G1 X104.113 Y97.661 E2.35499
G1 X104.104 Y98.178 E2.382
G1 X103.927 Y98.665 E2.40907
G1 X103.579 Y99.074 E2.43713
G1 X103.14 Y99.327 E2.4636
G1 X102.602 Y99.4 E2.49197
G1 X102.202 Y99.355 E2.513
G1 X101.784 Y99.166 E2.53697
G1 X101.521 Y98.987 E2.55359
G1 X101.413 Y98.952 E2.55952
G1 X101.205 Y99.086 E2.57245
G1 X101.298 Y99.731 E2.6065
G1 X100.869 Y99.947 E2.63159
G1 X100.664 Y99.95 E2.6423
;TYPE:External perimeter
;WIDTH:0.404381
;HEIGHT:0.3
G1 F600
G1 X100.191 Y99.955 E2.66236
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X100.011 Y99.957 E2.67176
;TYPE:External perimeter
;WIDTH:0.404381
;HEIGHT:0.3
G1 F600
G1 X99.525 Y99.962 E2.69237
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X98.685 Y99.971 E2.73626
G1 X98.385 Y99.912 E2.75223
G1 X98.334 Y99.7 E2.76362
G1 X98.622 Y99.497 E2.78203
G1 X99.159 Y98.898 E2.82406
G1 X99.542 Y98.785 F7800
G1 E.82406 F2400
G92 E0
G1 X97.802 Y100.556 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:0.404381
;HEIGHT:0.3
G1 F600
G1 X98.055 Y100.576 E2.01076
G1 X98.298 Y100.525 E2.02129
G1 X98.299 Y100.463 E2.02392
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X98.304 Y100.194 E2.03798
G1 X98.372 Y99.947 E2.05136
G1 X98.334 Y99.7 E2.06442
G1 X98.228 Y99.598 E2.07211
G1 X98.046 Y99.299 E2.0904
G1 X98.433 Y98.907 E2.11918
G1 X98.662 Y98.544 E2.1416
G1 X98.793 Y98.153 E2.16314
G1 X98.799 Y97.663 E2.18874
G1 X98.681 Y97.283 E2.20953
G1 X98.398 Y96.88 E2.23526
G1 X98.138 Y96.674 E2.25259
G1 X97.821 Y96.529 E2.2708
G1 X97.319 Y96.452 E2.29733
G1 X96.822 Y96.569 E2.32401
G1 X96.391 Y96.825 E2.3502
G1 X96.048 Y97.249 E2.37869
G1 X95.905 Y97.62 E2.39946
G1 X95.879 Y98.164 E2.42791
G1 X96.048 Y98.67 E2.45578
G1 X96.369 Y99.057 E2.48205
G1 X96.646 Y99.251 E2.49972
G1 X96.959 Y99.36 E2.51704
G1 X97.478 Y99.394 E2.54421
G1 X97.858 Y99.304 E2.56461
G1 X98.046 Y99.299 E2.57444
G1 X98.094 Y99.696 F7800
G1 E.57444 F2400
G92 E0
G1 X98.382 Y102.609 F7800
G1 E2 F2400
G1 F900
G1 X98.557 Y102.471 E2.01164
G1 X99.95 Y102.345 F7800
;TYPE:Perimeter
;WIDTH:0.398589
;HEIGHT:0.3
G1 F600
G1 X100.135 Y102.305 E2.01953
G1 X99.552 Y102.705 F7800
;TYPE:External perimeter
;WIDTH:0.45
G1 F600
G1 X99.626 Y102.085 E2.04956
G1 X99.864 Y102.002 E2.06168
;WIDTH:0.494034
G1 X100.074 Y101.972 E2.07305
;WIDTH:0.538068
G1 X100.283 Y101.942 E2.08552
;WIDTH:0.582102
G1 X100.493 Y101.912 E2.09922
;WIDTH:0.593651
G1 X100.805 Y101.731 E2.12303
;WIDTH:0.603031
G1 X101.071 Y101.352 E2.15414
;WIDTH:0.609623
G1 X101.073 Y101.193 E2.16495
G1 X100.894 Y100.883 E2.18929
G1 X101.292 Y100.947 E2.2167
G1 X101.497 Y101.056 E2.23249
G1 X101.631 Y101.192 E2.24547
G1 X101.595 Y101.476 E2.26494
;WIDTH:0.602827
G1 X101.404 Y101.813 E2.29095
;WIDTH:0.612779
G1 X101.368 Y101.963 E2.3015
G1 X101.165 Y102.108 E2.31856
;WIDTH:0.593651
G1 X100.756 Y102.358 E2.3502
;WIDTH:0.577392
G1 X100.603 Y102.449 E2.36159
;WIDTH:0.542814
G1 X100.45 Y102.539 E2.37218
;WIDTH:0.508236
G1 X100.296 Y102.63 E2.38208
;WIDTH:0.473659
G1 X99.804 Y102.728 E2.40769
;WIDTH:0.45
G1 X99.612 Y102.71 E2.41697
G1 X99.599 Y102.31 F7800
;LAYER_CHANGE
;Z:1.85
;HEIGHT:0.3
G1 E.41697 F2400
G92 E0
G1 Z1.85 F7800
G1 X97.836 Y100.575
G1 E2 F2400
;WIDTH:0.404381
G1 F600
G1 X97.815 Y100.612 E2.0018
G1 X97.751 Y100.575 E2.00493
G1 X97.815 Y100.538 E2.00806
G1 X96.982 Y99.374 F7800
G1 F600
G1 X96.83 Y99.33 E2.01477
G1 X96.424 Y99.107 E2.03441
G1 X96.086 Y98.743 E2.05547
G1 X95.976 Y98.508 E2.06647
G1 X95.868 Y98.1 E2.08437
G1 X95.905 Y97.589 E2.1061
G1 X96.103 Y97.113 E2.12796
G1 X96.288 Y96.899 E2.13996
G1 X96.345 Y97.295 F7800
G1 E.13996 F2400
G92 E0
G1 X101.394 Y99.333 F7800
G1 E2 F2400
G1 F600
G1 X101.373 Y99.369 E2.00177
G1 X101.309 Y99.333 E2.00488
G1 X101.373 Y99.296 E2.00801
G1 E.00801 F2400
G92 E0
G1 X101.342 Y101.439 F7800
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:0.38866
G1 F600
G1 X101.215 Y101.625 E2.00911
;WIDTH:0.426687
G1 X101.088 Y101.811 E2.01929
G1 X100.852 Y102.003 E2.03304
;WIDTH:0.394579
G1 X100.632 Y102.121 E2.04332
;WIDTH:0.420861
G1 X100.314 Y102.218 E2.0581
;WIDTH:0.447143
G1 X99.996 Y102.314 E2.07396
G1 X99.17 Y102.632 F7800
;TYPE:External perimeter
;WIDTH:0.630123
G1 F600
G1 X99.128 Y102.628 E2.07694
G1 X99.172 Y102.537 E2.08407
;WIDTH:0.585092
G1 X99.216 Y102.447 E2.09058
;WIDTH:0.540061
G1 X99.26 Y102.356 E2.09658
;WIDTH:0.49503
G1 X99.304 Y102.266 E2.10196
;WIDTH:0.45
G1 X99.513 Y102.106 E2.11462
G1 X99.874 Y101.949 E2.13355
G1 X100.542 Y101.775 E2.16675
G1 X100.775 Y101.599 E2.18079
G1 X101.081 Y101.227 E2.20396
G1 X101.242 Y101.105 E2.21368
G1 X101.421 Y101.055 E2.22262
G1 X101.689 Y101.136 E2.23609
G1 X101.725 Y101.227 E2.2408
G1 X101.718 Y101.465 E2.25225
G1 X101.458 Y101.9 E2.27662
G1 X101.453 Y102.031 E2.28293
G1 X100.938 Y102.374 E2.31269
G1 X100.395 Y102.626 E2.34148
G1 X99.87 Y102.731 E2.36723
;WIDTH:0.476866
G1 X99.612 Y102.691 E2.38066
;WIDTH:0.503732
G1 X99.354 Y102.652 E2.39496
;WIDTH:0.545862
G1 X99.279 Y102.644 E2.39949
;WIDTH:0.587992
G1 X99.23 Y102.638 E2.40271
G1 X99.294 Y102.244 F7800
G1 X98.701 Y103.075
;TYPE:Perimeter
;WIDTH:0.390835
G1 F600
G1 X98.681 Y103.111 E2.40439
G1 X98.653 Y103.095 E2.4057
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X98.619 Y103.075 E2.40776
G1 X98.681 Y103.04 E2.41148
G1 X98.195 Y103.045 F7800
;TYPE:External perimeter
;WIDTH:0.45
;HEIGHT:0.3
G1 F600
G1 X98.269 Y103.01 E2.41542
G1 X98.528 Y102.631 E2.4375
G1 X98.667 Y102.566 E2.44488
G1 X98.758 Y102.612 E2.44978
;WIDTH:0.422612
G1 X98.849 Y102.658 E2.45434
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X99.005 Y102.681 E2.46258
;TYPE:External perimeter
;WIDTH:0.387222
;HEIGHT:0.3
G1 F600
G1 X99.013 Y102.681 E2.4629
;WIDTH:0.432938
G1 X99.022 Y102.682 E2.46332
;WIDTH:0.478654
G1 X99.03 Y102.682 E2.46373
;WIDTH:0.524369
G1 X99.038 Y102.682 E2.46419
;WIDTH:0.570085
G1 X99.047 Y102.683 E2.46476
;WIDTH:0.6158
G1 X99.055 Y102.683 E2.46531
;WIDTH:0.63385
G1 X99.044 Y102.796 E2.47337
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X99.041 Y102.832 E2.47526
;TYPE:External perimeter
;WIDTH:0.625978
;HEIGHT:0.3
G1 F600
G1 X99.035 Y102.894 E2.47962
;WIDTH:0.581983
G1 X99.028 Y102.957 E2.48371
;WIDTH:0.537989
G1 X99.022 Y103.019 E2.48739
;WIDTH:0.493994
G1 X99.016 Y103.081 E2.49073
;WIDTH:0.45
G1 X99.135 Y103.341 E2.50448
G1 X98.994 Y103.366 E2.51137
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X98.982 Y103.368 E2.51201
;TYPE:External perimeter
;WIDTH:0.45
;HEIGHT:0.3
G1 F600
G1 X98.815 Y103.398 E2.52017
G1 X98.748 Y103.525 E2.52708
G1 X98.359 Y103.372 E2.54718
G1 X98.239 Y103.194 E2.5575
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X98.224 Y103.145 E2.56018
;TYPE:External perimeter
;WIDTH:0.45
;HEIGHT:0.3
G1 F600
G1 X98.212 Y103.103 E2.56228
G1 X98.433 Y102.77 F7800
G1 E.56228 F2400
G92 E0
G1 X102.669 Y97.929 F7800
G1 E2 F2400
;WIDTH:0.404381
G1 F600
G1 X102.648 Y97.966 E2.0018
G1 X102.584 Y97.929 E2.00493
G1 X102.648 Y97.892 E2.00806
;LAYER_CHANGE
;Z:2.15
;HEIGHT:0.3
G1 E.00806 F2400
G92 E0
G1 Z2.15 F7800
G1 X100.382 Y99.208
G1 E2 F2400
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X100.161 Y99.729 E2.02957
G1 X100.157 Y99.857 E2.03626
G1 E.03626 F2400
G92 E0
G1 X100.022 Y102.305 F7800
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:0.380099
;HEIGHT:0.3
G1 F600
G1 X100.141 Y102.267 E2.00492
G1 E.00492 F2400
G92 E0
G1 X100.448 Y100.237 F7800
G1 E2 F2400
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X101.043 Y100.66 E2.03814
;TYPE:External perimeter
;WIDTH:0.606286
;HEIGHT:0.3
G1 F600
G1 X101.239 Y100.808 E2.05474
G1 X101.602 Y101.141 E2.08803
G1 X101.638 Y101.244 E2.0954
G1 X101.567 Y101.523 E2.11486
;WIDTH:0.611742
G1 X101.322 Y101.894 E2.14521
G1 X101.337 Y101.964 E2.1501
G1 X100.728 Y102.343 E2.19907
;WIDTH:0.573766
G1 X100.566 Y102.429 E2.21072
;WIDTH:0.53251
G1 X100.404 Y102.516 E2.22146
;WIDTH:0.491255
G1 X100.242 Y102.603 E2.23125
;WIDTH:0.45
G1 X99.801 Y102.668 E2.25269
G1 X99.473 Y102.609 E2.26872
G1 X99.346 Y102.534 E2.27581
G1 X99.333 Y102.357 E2.28435
G1 X99.502 Y102.158 E2.29691
G1 X99.954 Y101.956 E2.32072
;WIDTH:0.494871
G1 X100.123 Y101.936 E2.32986
;WIDTH:0.539743
G1 X100.292 Y101.916 E2.33995
;WIDTH:0.584615
G1 X100.461 Y101.896 E2.35099
G1 X100.677 Y101.801 E2.3663
;WIDTH:0.581344
G1 X100.974 Y101.495 E2.3938
;WIDTH:0.606286
G1 X101.088 Y101.285 E2.40995
G1 X101.024 Y101.023 E2.42818
G1 X100.878 Y100.824 E2.44486
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X100.484 Y100.286 E2.4797
G1 X100.822 Y100.499 F7800
G1 E.4797 F2400
G92 E0
G1 X98.78 Y103.073 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:0.608545
;HEIGHT:0.3
G1 F600
G1 X98.841 Y103.329 E2.01786
;LAYER_CHANGE
;Z:2.45
;HEIGHT:0.3
G1 Z2.45 F7800
G1 X99.45 Y102.017
;WIDTH:0.561575
G1 F600
G1 X99.356 Y101.877 E2.02832
;WIDTH:0.559623
G1 X99.34 Y101.841 E2.03075
;WIDTH:0.51392
G1 X99.324 Y101.804 E2.03301
;WIDTH:0.468217
G1 X99.308 Y101.768 E2.03499
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X99.129 Y101.37 E2.05779
G1 X99.008 Y101.235 E2.06726
G1 E.06726 F2400
G92 E0
G1 X100.709 Y98.205 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:0.621864
;HEIGHT:0.3
G1 F600
G1 X100.719 Y98.157 E2.00341
;WIDTH:0.651502
G1 X100.73 Y98.11 E2.00694
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X100.751 Y98.022 E2.01167
;TYPE:External perimeter
;WIDTH:0.654095
;HEIGHT:0.3
G1 F600
G1 X100.785 Y97.872 E2.02298
;WIDTH:0.630204
G1 X100.743 Y97.829 E2.02722
;WIDTH:0.587334
G1 X100.7 Y97.786 E2.03119
;WIDTH:0.544464
G1 X100.657 Y97.744 E2.03479
;WIDTH:0.501593
G1 X100.614 Y97.701 E2.03811
;WIDTH:0.458723
G1 X100.571 Y97.659 E2.04107
;WIDTH:0.452033
G1 X100.327 Y97.569 E2.05364
G1 X100.217 Y97.412 E2.06291
G1 X100.53 Y97.661 F7800
G1 E.06291 F2400
G92 E0
G1 X100.353 Y99.83 F7800
G1 E2 F2400
;WIDTH:0.452135
G1 F600
G1 X100.505 Y100.037 E2.01242
;WIDTH:0.480661
G1 X101.541 Y101.034 E2.08707
;WIDTH:0.480183
G1 X101.592 Y101.236 E2.09787
;WIDTH:0.475726
G1 X101.536 Y101.466 E2.11001
;WIDTH:0.446135
G1 X101.338 Y101.755 E2.12669
;WIDTH:0.484748
G1 X101.327 Y101.879 E2.13322
G1 X101.068 Y102.053 E2.14958
;WIDTH:0.458262
G1 X100.808 Y102.226 E2.16492
;WIDTH:0.452438
G1 X100.331 Y102.414 E2.18974
;WIDTH:0.458144
G1 X99.787 Y102.533 E2.21709
;WIDTH:0.487654
G1 X99.464 Y102.482 E2.23435
;WIDTH:0.524614
G1 X99.457 Y102.25 E2.24767
;WIDTH:0.561575
G1 X99.45 Y102.017 E2.26213
G1 X99.515 Y102.074 E2.26749
;WIDTH:0.532204
G1 X99.579 Y102.13 E2.27245
;WIDTH:0.502833
G1 X99.747 Y102.144 E2.28167
;WIDTH:0.458144
G1 X100.241 Y102.036 E2.3065
;WIDTH:0.452438
G1 X100.646 Y101.892 E2.3273
;WIDTH:0.43717
G1 X101.122 Y101.479 E2.3566
;WIDTH:0.442381
G1 X101.158 Y101.383 E2.36143
;WIDTH:0.474837
G1 X101.194 Y101.286 E2.36673
;WIDTH:0.484626
G1 X100.979 Y101.048 E2.38354
G1 X100.606 Y100.705 E2.4101
;WIDTH:0.480661
G1 X100.362 Y100.427 E2.42931
;WIDTH:0.453965
G1 X100.118 Y100.15 E2.44725
;WIDTH:0.430929
G1 X99.966 Y99.841 E2.46299
G1 X100.016 Y99.571 E2.47554
;WIDTH:0.420872
G1 X100.213 Y99.068 E2.49956
;WIDTH:0.421616
G1 X100.382 Y98.388 E2.53078
G1 X100.474 Y98.389 E2.53488
;WIDTH:0.469879
G1 X100.553 Y98.349 E2.53936
;WIDTH:0.518143
G1 X100.633 Y98.309 E2.54442
;WIDTH:0.555185
G1 X100.671 Y98.257 E2.54836
;WIDTH:0.592227
G1 X100.709 Y98.205 E2.5526
G1 X100.706 Y98.304 E2.55912
;WIDTH:0.549574
G1 X100.703 Y98.404 E2.56517
;WIDTH:0.506921
G1 X100.7 Y98.504 E2.57069
;WIDTH:0.464268
G1 X100.697 Y98.604 E2.57568
;WIDTH:0.421616
G1 X100.551 Y99.179 E2.60211
;WIDTH:0.420872
G1 X100.363 Y99.643 E2.62437
;WIDTH:0.430929
G1 X100.34 Y99.776 E2.63054
G1 X100.578 Y100.097 F7800
;LAYER_CHANGE
;Z:2.75
;HEIGHT:0.3
G1 E.63054 F2400
G92 E0
G1 Z2.75 F7800
G1 X97.977 Y100.634
G1 E2 F2400
;WIDTH:0.461739
G1 F600
G1 X98.224 Y100.741 E2.01334
;WIDTH:0.495934
G1 X98.463 Y100.898 E2.02873
;WIDTH:0.530129
G1 X98.701 Y101.055 E2.04529
;WIDTH:0.564325
G1 X98.94 Y101.211 E2.06309
G1 X99.098 Y101.383 E2.07765
;WIDTH:0.522887
G1 X99.482 Y102.147 E2.12655
;WIDTH:0.517787
G1 X99.531 Y102.237 E2.13235
G1 X99.274 Y101.93 F7800
G1 E.13235 F2400
G92 E0
G1 X100.706 Y100.531 F7800
G1 E2 F2400
;WIDTH:0.404381
G1 F600
G1 X100.305 Y100.1 E2.02496
G1 X100.188 Y99.889 E2.03519
G1 X100.17 Y99.748 E2.04122
G1 X100.34 Y99.256 E2.06329
G1 X100.378 Y99.655 F7800
G1 E.06329 F2400
G92 E0
G1 X100.441 Y97.525 F7800
G1 E2 F2400
G1 F600
G1 X100.419 Y97.562 E2.00183
G1 X100.356 Y97.525 E2.00493
G1 X100.419 Y97.488 E2.00803
G1 E.00803 F2400
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; objects_info = {"objects":[]}
; filament used [mm] = 9.04
; filament used [cm3] = 0.02
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 24s
; estimated first layer printing time (normal mode) = 6s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; bed_temperature_extruder = 0
; before_layer_gcode = 
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights = 
; complete_objects = 0
; cooling = 1
; cooling_perimeter_transition_distance = 0
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; custom_parameters_filament = ""
; custom_parameters_print = 
; custom_parameters_printer = 
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_abrasive = 0
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = "- default -"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; filament_wipe = nil
; fill_angle = 45
; fill_density = 20%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_height = 0.35
; first_layer_infill_speed = 0
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = reprap
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.3
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_max_junction_deviation = 0,0
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 35
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = - default -
; printer_model = 
; printer_notes = 
; printer_settings_id = - default FFF -
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_short_distance_acceleration = 0
; travel_slope = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
